import PDFDocument from "pdfkit";

export function buildPaymentPdf({ payment, event, payer, items, type }) {
  const doc = new PDFDocument({ margin: 50 });

  doc.fontSize(18).text(type === "RECEIPT" ? "Receipt" : "Invoice", { align: "right" });
  doc.moveDown(0.5);

  doc.fontSize(12).text(`Invoice No: ${payment.invoiceNo || "-"}`);
  doc.text(`Transaction Ref: ${payment.transactionRef}`);
  doc.text(`Status: ${payment.status}`);
  if (payment.paidAt) doc.text(`Paid At: ${payment.paidAt.toISOString()}`);
  doc.moveDown();

  doc.fontSize(14).text("Event");
  doc.fontSize(12).text(event?.name || event?.title || "Event");
  doc.moveDown();

  doc.fontSize(14).text("Billed To");
  doc.fontSize(12).text(payer?.name || "Payer");
  doc.text(payer?.email || "");
  doc.moveDown();

  doc.fontSize(14).text("Items");
  doc.fontSize(12);

  let subtotal = 0;
  items.forEach((it) => {
    const lineTotal = it.total ?? (it.qty * it.unitPrice);
    subtotal += lineTotal;
    doc.text(`${it.description}  |  Qty: ${it.qty}  |  Unit: ${it.unitPrice}  |  Total: ${lineTotal}`);
  });

  doc.moveDown();
  doc.fontSize(12).text(`Subtotal: ${subtotal}`);
  doc.fontSize(12).text(`Total: ${subtotal} ${payment.currency}`);

  doc.moveDown(2);
  doc.fontSize(10).text("Generated by University Event System", { align: "center" });

  return doc;
}
